name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: cd test_app && yarn install
      - name: Cypress
        uses: cypress-io/github-action@v1
        with:
          start: yarn start
